---
- name: Install Lua 5.1
  apt: pkg=lua5.1

- name: Install luarocks
  apt: pkg=luarocks

- name: Install Orbit
  command: luarocks install orbit

- name: Install libsqlite3-dev
  apt: pkg=libsqlite3-dev

- name: Install luasql-sqlite3
  command: luarocks install luasql-sqlite3

- name: Install json4lua
  command: luarocks install JSON4Lua
